export const INITIALIZE_USER = "INITIALIZE_USER";
export const RESET_USER = 'RESET_USER'
export const SET_USER_FIREBASE_DATA = 'SET_USER_FIREBASE_DATA'
export const SET_AUTHENTICATING_USER = 'SET_AUTHENTICATING_USER'
export const SET_VERIFICATION_STATUS = "SET_VERIFICATION_STATUS";
